version: '3'

services:
  web:
    build: ./
    links:
      - mysql:mysql
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local