version: '3'

networks:
  default:
    external:
      name: shared_network

services:
  application-service:
    build: ./
    links:
      - mysql:mysql
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysqlPW
      MYSQL_DATABASE: easy-parking
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local